name: technephilosophos
favicon: null
layout_spectrum: 0.2612345889210701
typography_spectrum: 0.6172587329056114
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.05531712924130261
  lightness: 0.9085745941847563
  saturation: 0.3028996589127928
  rhythmicContrast: 0.9068011743947864
purpose: []
